export const firstRootLabel = '//div[@class="docs-example"]/ul/li[1]/div/label'
export const child212Label = '//div[@class="docs-example"]/ul/li[1]/ul[1]/li[2]/div/label'
export const grand1121Label = '//div[@class="docs-example"]/ul/li[1]/ul[1]/li[2]/ul[1]/li[1]/div/label'
export const valuePreviewDiv = '//div[@class="docs-example"]/div[1]'
export const selectAbleToggle = '//div[@class="docs-example"]/div[2]/div/label'
